### ISSUE TITLE
Fastlane: changelog over limit

### ISSUE THREAD

**Issue by IzzySoft** [NimaKhajehpour/MyMood#17]
Just a note: Fastlane's per-release changelogs are limited to 500 chars. Your `3.txt` has 538 chars, and thus will be truncated. Removing the leading spaces before the bullet points and the "in this version" intro would solve it for the current one.

**Comment by NimaKhajehpour** [comment]
Hey @IzzySoft thanks for the heads-up i did not realize that. I apply the changes. But the main problem on the app right now is the RB which failed and i do not have any idea why it happened. I looked at everything and nothing seemed off. Feel free to check the issue on that idf you can and give me your idea on it. The issue is #15
Any ways thanks for the reminder on changelog length ❤️

**Comment by IzzySoft** [comment]
> i did not realize that.

Thought so – hence the heads-up :smile: If "that" means you didn't realize there **are** such limits, you might wish to take another look at my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) concerning the other limits, before you accidentally happen to cross them :wink: In short: 80 char for shortdesc, 4000 char for fulldesc – plus some numbers for the graphics.

> RB which failed and i do not have any idea why it happened

Not exactly my specialty – licaon is better at that, linsui has more experience with it, and finally the one who documented everything on the topic, obfusk… I can tell general places only, mostly. Like, what licaon meant: your build must be from the very same commit used at F-Droid (which is the one the tag points to). Then your saying something seems amiss which clearly should be there: make sure you have no uncommitted changes (sometimes one forgets to add a change before committing).

One wild thought: you wrote you changed the tag after the failed build at F-Droid. I'm not 100% sure what point of the source tree is kept at F-Droid, but it might still use the "previous tag with the same name". So maybe get everything clean & stable, then tag a **new** release – if needed, a "maintenance release" like `v1.2.1` if no `v1.3.0` is due yet? That would at least make sure the new tag gets pulled.

**Comment by NimaKhajehpour** [comment]
>  If "that" means you didn't realize there are such limits

no by "that" i meant i did not realize it got over limit 😅 

>  your build must be from the very same commit used at F-Droid

Yeah i did check that and it is from the same commit on f-droid because every time i make a new tag i build the newest release and i make sure everything matches the changes on code. But again i guess i have to test that theory as well.

> make sure you have no uncommitted changes

I did check that too, i saw the diff log and it was strange to me so i checked that and it was fine too

>  you wrote you changed the tag after the failed build at F-Droid

Yup i did have the same thought and i shared it with licaon and they gave me the link to the changes on the config file, the commit was the updated one so i guess the tag should be the updated one too right?

 > if needed, a "maintenance release" like v1.2.1 if no v1.3.0 is due yet?

so for the release if i release a maintenance release like 1.2.1, what will happen to this release. do we just not publish this one and instead the other tag goes up? then if this release which is version name 3 does not need to have changes on changelog and i just put the shortened one for version name 4?

also thanks for giving me your ideas on the problem i will get working on it and see which could be the solution.

**Comment by IzzySoft** [comment]
OK, so you had the same ideas already, hm… I didn't follow all the details you exchanged with licaon, so I have to pass on that part.

As for the maintenance release: yes, the "failed one" would be skipped then. But you should **always** increase `versionCode` when making a new release. That must become "muscle memory" so you cannot ever forget. Someone might have picked that APK from your Github releases waiting for the new version, and thus would miss the next one, for example.

And best luck getting it up again!

**Comment by NimaKhajehpour** [comment]
Yeah i learned my lesson with this build. Not to delete a tag and put the new release on same tag name. I dont know what was mt thought process that i did not release a new version 😥
Ok so i will get the maintenance release up, i dont think i will make any changes i will just bump the version and get going with the updates.
Thanks for the help both you and licaon that put your time in this ❤️

**Comment by IzzySoft** [comment]
Yeah, guess that's one of the reasons we say "never replace a tag once F-Droid has built from it". If the new tag works, Ill have to adjust that phrase to "once F-Droid **started** building from it", including failed builds.

**Comment by NimaKhajehpour** [comment]
Yeah this was a good lesson for me nit to re-release a tag. Another lesson taken 😀

**Comment by IzzySoft** [comment]
So if your build succeeds on the next cycle, we've both learned something from it :laughing:

**Comment by NimaKhajehpour** [comment]
well the RB failed the same way :disappointed:

**Comment by IzzySoft** [comment]
Sad. Maybe obfusk can help with that – if even licaon is out of ideas…

**Comment by NimaKhajehpour** [comment]
Yeah, you recon i ping them in the issue?

**Comment by IzzySoft** [comment]
I cannot be everywhere (though it might seem so to some :see_no_evil:)
